### ISSUE TITLE
int should be int32 in GetDTLAt()

### ISSUE THREAD

**Issue by ThinkontrolSY** [robinson/gos7#21]
https://github.com/robinson/gos7/blob/929a8656546f34c7c6196bd31cefefc78ee399e6/helper.go#L177

nsec in S7 is a UDInt, which is 4 word (32bit) length, 
int size may 32bit or 64bit  depend on cpu architecture, may cause problem when running on 64bit cpu

**Comment by robinson** [comment]
Hi @ThinkontrolSY,
highly appreciated for point this out and some other issues as well. Could you please take a pull request thi fix them up if you could. Many thanks for your contributing, Robinson
