### ISSUE TITLE
Please explain differentce between S7 and Profinet?

### ISSUE THREAD

**Issue by Serhioromano** [robinson/gos7#25]
I have an application that has to be able to read data from all Siemens PLC like 200, 300, 400, 1200.

I am not good at Siemens I am more like WAGO\Codesys\Modbus world user. I always thought that PROFINET is an analog of MODBUS in the siemens world. Now I find this library. Another protocol?

On another site, I read

> The S7 protocol is designed for transferring data into SCADA systems via Ethernet. The PROFINET protocol is used for communication between PLCs and IO modules.

That sounds reasonable. Does that mean that people do not use PROFINET to communicate to Siemens PLC for SCADA? My app is a little SCADA for a particular project with S7 1200 PLCs. I need to show a few tags only. Why would I choose S7 over PROFINET?

**Comment by robinson** [comment]
Hi @Serhioromano, 1st question: I guess so, industrial product has many option to define communciation between Siemens PLC to SCADA, even thur OPC standard or anything. 
2nd question: You can choose whatever you want, my perspective is S7 communcating directly to my PLC, if they are a small size of blocks and posibly handle them.
