### ISSUE TITLE
read  addresses from wincc

### ISSUE THREAD

**Issue by gharsallahmoez** [robinson/gos7#43]
I get addresses from wincc that communicate with PLC S7-300, 
example from those addresses : 
DB12522,DBB28 (of type byte)
DB14030,DBW6 (of type word)
DB5200,DD2320 (of type float)
DB6200,D206.1 (of type boolean)

can anybody please share an example of how to read it with the gos7 library? please note that I can read all those data using OPC(KEPServerEX)

**Comment by robinson** [comment]
@gharsallahmoez gos7 support call directly S7 device. If you want to read this thru OPC, you should have to use any OPC client, for example: kepware opc client.
Hope that helps
