### ISSUE TITLE
Request support for some S7-200

### ISSUE THREAD

**Issue by wind-j** [robinson/gos7#54]
Hello, I need to use the SetConnectionParameters function when using some S7-200 devices.
Can you modify the support? Thanks!

**Comment by robinson** [comment]
Hi wind-j, actually I tested it with S7-200 some years ago, cannot remember it correctly, can you set rack and slot as 0 and 0 and it should work. BR

**Comment by wind-j** [comment]
Thank you, I will try it when I have debugging conditions.
